server: 
  port: 9001
spring: 
  application:  
    name: education-course-[path_3] #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/education?characterEncoding=UTF8
    username: root
    password: cgk
  jpa:
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 127.0.0.1