server:
  port: 6868
  servlet:
    application-display-name: education-eureka
spring:
  freemarker:
    prefer-file-system-access: false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    hostname: localhost